export default{
	"COMMON": {
		"terminate": "finish",
		"days": "Days",
		"previous": "Precedent",
		"next": "following",
		"mailNotification": "Alerts by email",
		"mailNotificationThreshold": "Receive alarms on thresholds",
		"LORA_DEVICE_NOT_FOUND": "The device does not exist",
		"mailNotificationTechnical": "Receive technical alarms",
		"mailNotificationTitle": "Alert Management",
		"LORA_DEVICE_ALREADY_REGISTERED": "The device is already registered",
		"LORA_DEVICE_SITE_NOT_FOUND": "The site was not found",
		"selectAll": "Select all",
		"unselectAll": "Unselect All",
		"all": "All",
		"cancel": "Cancel",
		"ok": "OK",
		"all_female": "All",
		"valid": "Validate",
		"send": "To send",
		"add": "Add",
		"save": "Record",
		"defaultZoneName": "Default area",
		"delete": "Remove",
		"date": "Dated",
		"hour": "Hour",
		"channel": "way",
		"channelInternal": "internal",
		"unit_unknown": "Unspecified unit",
		"errorFieldsMandatory": "Please fill all fields",
		"errorConfirmationMismatch": "Confirmation password does not match",
		"errorMaxProfile": "Maximum number of profiles reached",
		"errorNameExists": "Profile name is not available",
		"USER_EXISTS": "Username is not available",
		"MAIL_EXISTS": "The email address is not available",
		"LICENSE_CODE_INVALID": "The subscription code is invalid",
		"USER_OR_MAIL_EXISTS": "Username or email are not available",
		"LICENSE_USED": "The subscription code has already been used",
		"LICENSE_MAX_USERS": "You have reached the limit of the number of active users",
		"LICENSE_MAX_READ_DATA": "You can only view data over a rolling {1} month period",
		"LICENSE_MAX_SLAVES": "You have reached the limit of the number of active devices",
		"LICENSE_KEY_INVALID": "Product code is invalid",
		"MASTER_NOT_FOUND": "License not found",
		"SITE_EXISTS": "The site is already registered on another account",
		"lastName": "Name",
		"login": "Connection identifier",
		"firstName": "Firstname",
		"mail": "Mail address",
		"confirmation": "Confirmation",
		"password": "Password",
		"name": "Name",
		"unit_0": "any",
		"unit_1": "m/s",
		"unit_2": "fpm",
		"unit_4": "L/s",
		"unit_3": "m3/h",
		"unit_5": "cfm",
		"unit_6": "m3/s",
		"unit_7": "°C",
		"unit_10": "PSI%",
		"unit_8": "°F",
		"unit_9": "% RH",
		"unit_11": "Pa",
		"unit_13": "INWG",
		"unit_12": "mmH2O",
		"unit_15": "mmHg",
		"unit_14": "kPa",
		"unit_16": "mbar",
		"unit_17": "absolueg/kg",
		"unit_18": "°C Td",
		"unit_19": "°F Td",
		"unit_20": "°C Tw",
		"unit_21": "°F Tw",
		"unit_22": "kJ/kg",
		"unit_24": "AT",
		"unit_25": "mV",
		"unit_23": "my",
		"unit_26": "V",
		"unit_27": "lux",
		"unit_31": "free unit",
		"unit_32": "pulse",
		"unit_33": "pulse",
		"unit_34": "Kelvink",
		"unit_35": "km/h",
		"unit_36": "mph",
		"unit_37": "Hz",
		"unit_38": "rev/min",
		"unit_39": "rpm",
		"unit_40": "m/min",
		"unit_41": "in/min",
		"unit_42": "bar",
		"unit_43": "daPa",
		"unit_44": "hPa",
		"unit_45": "ppm",
		"unit_46": "dB",
		"unit_lora_0": "any",
		"unit_47": "ohms",
		"unit_lora_1": "% RH",
		"unit_lora_2": "",
		"unit_lora_3": "free unit",
		"unit_lora_16": "°C",
		"unit_lora_15": "unknown unit",
		"unit_lora_17": "°F",
		"unit_lora_18": "K",
		"unit_lora_32": "% RH",
		"unit_lora_20": "Delta °F",
		"unit_lora_19": "Delta °C",
		"unit_lora_33": "g/kg",
		"unit_lora_37": "°C Tw",
		"unit_lora_34": "kJ/kg",
		"unit_lora_36": "°FTD",
		"unit_lora_35": "°Ctd",
		"unit_lora_38": "°F Tw",
		"unit_lora_48": "bar",
		"unit_lora_39": "g/m3",
		"unit_lora_50": "kPa",
		"unit_lora_49": "PSI",
		"unit_lora_51": "INWG",
		"unit_lora_53": "mbar",
		"unit_lora_54": "mmHg",
		"unit_lora_55": "mmH2O",
		"unit_lora_52": "hPa",
		"unit_lora_56": "daPa",
		"unit_lora_57": "Pa",
		"unit_lora_65": "fpm",
		"unit_lora_66": "km/h",
		"unit_lora_64": "m/s",
		"unit_lora_67": "mph",
		"unit_lora_80": "m3/h",
		"unit_lora_82": "cfm",
		"unit_lora_83": "m3/s",
		"unit_lora_81": "l/s",
		"unit_lora_84": "Nm3/h",
		"unit_lora_85": "dm3/h",
		"unit_lora_97": "rev/min",
		"unit_lora_98": "rpm",
		"unit_lora_96": "Hz",
		"unit_lora_99": "m/min",
		"unit_lora_101": "ft/min",
		"unit_lora_100": "in/min",
		"unit_lora_102": "m/s",
		"unit_lora_112": "ppm",
		"unit_lora_113": "mg/m3",
		"unit_lora_115": "g/kWh",
		"unit_lora_114": "mg/kWh",
		"unit_lora_117": "g/m3",
		"unit_lora_116": "g/GJ",
		"unit_lora_118": "%",
		"unit_lora_119": "% LIE",
		"unit_lora_120": "g/year",
		"unit_lora_129": "fc",
		"unit_lora_128": "lux",
		"unit_lora_130": "W/m2",
		"unit_lora_131": "klux",
		"unit_lora_132": "kfc",
		"unit_lora_144": "db",
		"unit_lora_160": "mV",
		"unit_lora_161": "V",
		"unit_lora_163": "my",
		"unit_lora_162": "ÂμA",
		"unit_lora_164": "AT",
		"unit_lora_165": "ohms",
		"unit_lora_176": "WBGT",
		"unit_lora_192": "s",
		"unit_lora_177": "W/m2/K",
		"unit_lora_193": "min",
		"unit_lora_194": "h",
		"unit_lora_208": "mm",
		"unit_lora_209": "in",
		"unit_lora_210": "m",
		"source_0": "Application",
		"unit_lora_255": "counting",
		"source_1": "Device",
		"source_2": "Deported Alarm",
		"source_4": "Communication Base",
		"source_3": "Calculated channel",
		"source_5": "Cloud",
		"code_1": "Application Launched",
		"code_2": "Application Closed",
		"code_4": "Editing Messaging Settings",
		"code_3": "Modification Preferences",
		"code_10": "User Login",
		"code_11": "User Logout",
		"code_12": "Connection Fail",
		"code_15": "Delete User",
		"code_14": "User Modification",
		"code_13": "Add User",
		"code_16": "Change Password",
		"code_17": "Add Group",
		"code_18": "Group Modification",
		"code_20": "User Management Modified",
		"code_19": "Delete Group",
		"code_100": "RF Device pairing",
		"code_101": "RF Device Removal",
		"code_102": "RF Device Replacement",
		"code_103": "RF Device Placement",
		"code_104": "RF Device Removal",
		"code_105": "Gray RF Device",
		"code_107": "Network Verification Configuration",
		"code_106": "Degray RF Device",
		"code_108": "Download Planning",
		"code_109": "Measures Planning",
		"code_201": "Device Configuration",
		"code_203": "Launch Campaign By PC",
		"code_204": "Stop Campaign By PC",
		"code_202": "Device Unloading",
		"code_205": "Device emptying",
		"code_206": "Reading Device Measurements",
		"code_207": "Test Communication",
		"code_1001": "Added Product",
		"code_1003": "Deleted Product",
		"code_1002": "Product Information Changed",
		"code_2001": "Added Deported Alarm",
		"code_2004": "Device Relay Control",
		"code_2002": "Deported Alarm Modified",
		"code_2003": "Deported Alarm Deleted",
		"code_2005": "Alarm Email Added",
		"code_2006": "Modified Email Alarm",
		"code_3001": "Initiation Service",
		"code_2008": "Email Alarm Sent",
		"code_2007": "Alarm Email Deleted",
		"code_3002": "Service Stopped",
		"code_5001": "Failed connection",
		"code_5002": "Restablished connection",
		"probe_1": "Ambiant NTC temperature",
		"code_5003": "Failed to send data",
		"code_5004": "Server request",
		"probe_2": "Internal NTC temperature",
		"probe_3": "Deported NTC temperature",
		"probe_5": "Current 4/20 mA",
		"probe_4": "Curent 0/20 mA",
		"probe_6": "Voltage 0/10 V",
		"probe_7": "Voltage 0/2500 mV",
		"probe_8": "Ambiant Thermo-Hygro SHT",
		"probe_10": "Brightness",
		"probe_9": "Deported Thermo-Hygro SHT",
		"probe_11": "Temperature Thermocouple K",
		"probe_12": "Temperature Thermocouple T",
		"probe_13": "Temperature Thermocouple J",
		"probe_15": "Ambiant Thermo-Hygro",
		"probe_14": "PT100 temperature deported",
		"probe_16": "Thermo-Hygro Inox deported",
		"probe_17": "Current Clamp 20 A",
		"probe_18": "Current Clamp 50 A",
		"probe_19": "Current Clamp 100 A",
		"probe_20": "Current Clamp 200 A",
		"probe_21": "Current Clamp 600 A",
		"probe_22": "Thermo-Hygro Plastic deported",
		"probe_23": "Temperature KT20",
		"probe_25": "Pulse detection",
		"probe_26": "Pulse counter",
		"probe_24": "Temperature Thermocouple S",
		"probe_27": "Pressure 1000 Pa",
		"Probe_29": "CO2 cell",
		"probe_28": "Pressure 10000 Pa",
		"Probe_lora_1": "Thermocouple K",
		"Probe_30": "Light",
		"Probe_lora_2": "Thermocouple J",
		"Probe_lora_3": "Thermocouple T",
		"Probe_lora_5": "Thermocouple S",
		"Probe_lora_6": "Current 0-20mA",
		"Probe_lora_4": "Thermocouple N",
		"Probe_lora_7": "4-20mA current",
		"Probe_lora_8": "0-5V voltage",
		"Probe_lora_10": "Pulse counter",
		"Probe_lora_11": "50A Ampere Clamp",
		"Probe_lora_9": "0-10V voltage",
		"Probe_lora_12": "Current Clamp 100A",
		"Probe_lora_13": "Current Clamp 200A",
		"Probe_lora_14": "Current Clamp 600A",
		"Probe_lora_15": "External NTC temperature",
		"Probe_lora_16": "external PT100 temperature",
		"Probe_lora_17": "Internal temperature",
		"Probe_lora_19": "Hygro-temperature probe",
		"Probe_lora_18": "Water pressure 0-10 bar",
		"Probe_lora_20": "Stainless steel hygro-temperature probe",
		"Probe_lora_21": "ABS hygro-temperature probe/amb",
		"Probe_lora_22": "Internal hygro-temperature",
		"Probe_lora_23": "Internal light",
		"Probe_lora_24": "Internal CO2",
		"Probe_lora_25": "Internal atmospheric pressure",
		"Probe_lora_26": "Internal pressure 1000 Pa",
		"Probe_lora_27": "Internal pressure 10000 Pa",
		"Probe_lora_28": "Water pressure 0-20 bar",
		"techAlarm_1": "Battery changed",
		"techAlarm_2": "Low battery",
		"techAlarm_3": "Communication Loss",
		"techAlarm_3_more": "No communication with the server since 1 hour",
		"techAlarm_4": "Communication restabliched",
		"techAlarm_666": "Error processing data",
		"techAlarm_510": "Error processing data.",
		"techAlarm_510_more": "510: No response from the database",
		"techAlarm_511": "Error processing data.",
		"techAlarm_511_more": "511: Unknown configuration version.",
		"techAlarm_512": "Error processing data.",
		"techAlarm_512_more": "512: Unconfigured device",
		"techAlarm_506": "Error processing data.",
		"techAlarm_506_more": "506: Device Configuration and Data Received Inconsistent",
		"techAlarm_514": "Error processing data.",
		"techAlarm_514_more": "514: Database error."
	},
	"LostPasswordForm": {
		"mail": "E-mail adress",
		"errorWrongMail": "Invalid email address",
		"title": "Username or password forgotten"
	},
	"InstallationTypeChoice": {
		"siteName": "name of the site",
		"siteSerial": "Identifier of the installation",
		"slaveSerial": "Serial number of the device",
		"slaveCode": "Device code"
	},
	"RegisterForm": {
		"login": "Connection identifier",
		"mail": "Mail",
		"register": "register",
		"licenseCode": "Subscription code",
		"confirmation": "Password Confirmation",
		"personalInformations": "Personal informations",
		"accountInformations": "Account settings",
		"siteInformations": "Site information"
	},
	"LoginForm": {
		"USER_INACTIVE": "Your access is disabled. ",
		"connexion": "Log in",
		"title": "Log in",
		"errorFieldsMandatory": "All fields are mandatory",
		"errorWrongLogin": "Incorrect username or password",
		"activationError": "An error occurred during activation",
		"activationSuccess": "Your account is now activated. ",
		"ERROR": "An error occurred while connecting. ",
		"lostPassword": "Username or password forgotten",
		"register": "Create an account",
		"registerSuccess": "Your registration has been taken into account",
		"lostPasswordSuccess": "An email containing your new password has been sent to the address"
	},
	"Menu": {
		"events": "Event Diary",
		"reporting": "Export",
		"unload": "Unload",
		"informations": "information",
		"settings": "Settings",
		"logoff": "Logoff",
		"configuration": "Configuration",
		"configure": "Configuration"
	},
	"SettingsPage": {
		"settings": "Settings"
	},
	"InformationsPage": {
		"informations": "information",
		"version": "Version",
		"documentation": "notice",
		"documentationLink": "Download the manual"
	},
	"SettingsUserAccessPage": {
		"title": "Management of user access"
	},
	"SettingsAccountPage": {
		"title": "My account"
	},
	"SettingsLicensePage": {
		"title": "Subscription",
		"renewLicenseTitle": "Subscription",
		"renewLicenseSubtitle": "Please enter your new subscription code",
		"licenseCode": "Subscription code",
		"licenseRenewSuccess": "Your new subscription is now active"
	},
	"SettingsUserPage": {
		"title": "User Management",
		"addUserSubtitle": "Please fill in the following fields",
		"login": "Connection identifier",
		"addUserTitle": "Add a user"
	},
	"SettingsProfilePage": {
		"title": "Profile Management",
		"addProfileTitle": "Adding a profile",
		"addProfileSubtitle": "Please fill in the following fields"
	},
	"UserList": {
		"login": "users",
		"role": "Group",
		"userSelection": "Selection of a user"
	},
	"ProfileList": {
		"profiles": "profiles",
		"profileSelection": "Selecting a profile"
	},
	"UserDetail": {
		"informations": "Account Information",
		"active": "Active account",
		"sites": "Accessible sites",
		"accesses": "access",
		"MODIFY_SUCCESS": "User successfully modified",
		"DELETE_SUCCESS": "User successfully deleted",
		"ADD_SUCCESS": "User successfully added",
		"confirmDelete": "Are you sure you want to delete this user?",
		"updatePassword": "change the password",
		"updatePasswordTitle": "Changing the password",
		"defaultProfile": "Default profile",
		"defaultZone": "Area not defined"
	},
	"AccountDetail": {
		"informations": "Account Information",
		"mail": "Mail address",
		"UPDATE_SUCCESS": "User successfully modified",
		"updatePasswordTitle": "Changing the password",
		"updatePassword": "change the password"
	},
	"ProfileDetail": {
		"informations": "Profile information",
		"active": "Active profile",
		"confirmDelete": "Are you sure you want to delete this profile?",
		"global": "General",
		"MODIFY_SUCCESS": "Profile modified successfully",
		"sites": "Accessible sites",
		"ADD_SUCCESS": "Profile successfully added",
		"DELETE_SUCCESS": "Profile deleted successfully",
		"accessType": "Type of access",
		"API_ADMIN_MANAGE_PROFILES": "Profile Management",
		"API_ADMIN_MANAGE": "Rights management",
		"API_ADMIN_MANAGE_USERS": "User Management",
		"API_USERS_ADD_SITES": "adding",
		"aclAffectation": "Assignment of rights",
		"API_SITES_MANAGE_SLAVES": "Device Management",
		"API_SITES_CONFIGURE_SLAVES": "Device configuration",
		"API_ALARMS_UPDATE": "Acknowledging alarms",
		"API_SITES_UPDATE_SLAVES": "Enable/Disable",
		"API_USERS_MANAGE_SITES": "Site Management",
		"API_USERS_UPDATE_SITES": "Name change",
		"API_SITES_MANAGE_ZONES": "Management of zones/groups of devices",
		"PROFILE_USED": "You can not delete a profile attached to a user"
	},
	"UserAccessList": {
		"success": "Registration successfully completed",
		"login": "User"
	},
	"SettingsSideBar": {
		"settings": "Settings",
		"users": "users",
		"profiles": "profiles",
		"account": "My account",
		"userAccesses": "User access",
		"groups": "Groups",
		"license": "Subscription"
	},
	"AdminPage": {
		"yes": "Yes",
		"userList": "List of users you can take control of",
		"site": "name of the site",
		"master": "Serial number",
		"activated": "Account activated",
		"no": "No",
		"search": "Research"
	},
	"SitePage": {
		"siteList": "List of your sites",
		"helpAddSite": "Add your sites by clicking on the icon () to access the data of your devices.",
		"siteName": "site's name",
		"serial": "Site identifier",
		"addSiteSubtitle": "Please enter the information of the site to add",
		"MASTER_NOT_FOUND": "License not found",
		"CONTROL_EXISTS": "The site is already registered on another account",
		"welcome": "Welcome to Medifroid Cloud",
		"addSiteTitle": "Adding a site"
	},
	"HomePage": {
		"waitingZoneName": "Devices waiting for configuration",
		"unload": "Forced unloading",
		"ZONE_DEFAULT": "You can not change the default area",
		"editZoneTitle": "Edit area",
		"addZoneTitle": "Add a area",
		"zoneName": "Name of the area",
		"addZone": "Add a zone",
		"editZone": "Edit an area",
		"siteName": "name of the site",
		"editSite": "Modification of the site",
		"confirmZoneDelete": "Are you sure you want to delete this area?",
		"confirmDelete": "Are you sure you want to delete this site?",
		"confirmChangeSlaveStatus": "Caution: Measurements and alarms on this device will no longer be sent to the cloud if you unmount it."
	},
	"NavBar": {
		"feedbackTitle": "Your opinion interests us",
		"profile": "Profile",
		"settings": "Settings",
		"logout": "Logout",
		"feedbackSubtitle": "Please enter your opinion"
	},
	"SideBar": {
		"alarm": "Alarms list",
		"slaves": "Devices list"
	},
	"SlaveList": {
		"slaves": "Devices list"
	},
	"ChannelList": {
		"measures": "Latest measurements taken",
		"values": "Values",
		"noMeasures": "No measures taken",
		"statistics": "Statistics",
		"dataViewMode0": "Graphic",
		"dataViewMode2": "Summary",
		"dataViewMode1": "Table",
		"dataViewMode3": "Configuration",
		"minimum": "Minimum",
		"average": "Average",
		"maximum": "Maximum",
		"deviation": "Standard deviation",
		"mkt": "MKT"
	},
	"ChannelListTable": {
		"values": "Values",
		"statistics": "Statistics",
		"minimum": "Minimum",
		"maximum": "Maximum",
		"deviation": "Standard deviation",
		"average": "Average",
		"mkt": "MKT"
	},
	"SlaveAbstract": {
		"comments": "Comment",
		"device": "Device",
		"configuration": "Configuration",
		"channels": "Channels",
		"reference": "Device",
		"serial": "Serial number",
		"designation": "Designation",
		"version": "Version",
		"campaign": "Campaign",
		"logType": "Registration type",
		"logType_0": "Deffered",
		"logType_1": "Instant",
		"logType_2": "Minimum",
		"logType_3": "Maximum",
		"logType_4": "Average",
		"logType_5": "Monitoring",
		"logType_6": "Online",
		"logType_7": "End",
		"logType_8": "Thermometer",
		"logType_9": "thermohygrometer",
		"logType_10": "Pulse detection",
		"recordDelay": "Recording interval",
		"measureInterval": "Measurement interval",
		"startDate": "Starting Date",
		"endDate": "End date",
		"probeType": "Probe type",
		"alarmState": "Alarm state",
		"alarmState_0": "Normal",
		"alarmState_1": "Active",
		"highThreshold": "High threshold",
		"lowThreshold": "Low threshold",
		"minute": "min.",
		"alarmState_2": "No configured alarms",
		"noAlarmState": "No configured alarms",
		"waitForConfigurationValidation": "Configuration pending validation"
	},
	"AlarmList": {
		"alarms": "alarms",
		"sameComment": "Apply the same comment to all alarms",
		"slaveDesignation": "Designation of the device",
		"value": "Value",
		"mode": "State",
		"filterAcked": "Acknowledged alarms",
		"filterUnacked": "Unacknowledged alarms",
		"filterNone": "All alarms",
		"ack": "acquit",
		"channelDesignation": "Designation of the channel",
		"ackPending": "Acquittal in progress ...",
		"modalSubtitle": "Leave a message before acknowledging the alarm",
		"oneAckAlarm": "Please select at least one alarm to acknowledge",
		"modalTitle": "Comment (optional)"
	},
	"DateFilterList": {
		"TODAY": "Today",
		"YESTERDAY": "Since yesterday",
		"WEEK": "Last 7 days",
		"MONTH": "Last 30 days",
		"INTERVAL": "Between two dates",
		"UNACKED": "Unacknowledged alarms",
		"ACKED": "Acknowledged alarms",
		"ALL": "All alarms",
		"LATEST": "Latest data"
	},
	"UnloadList": {
		"unload": "Unload",
		"unloadTitle": "Unload",
		"modalTitle": "Unloading in progress",
		"modalSubtitle2": "You can continue using the application while updating data",
		"oneUnload": "Please select at least one device",
		"modalSubtitle1": "This operation may take a few minutes.",
		"unloadSubtitle": "Select devices to unload"
	},
	"LogEventList": {
		"events": "Event Diary",
		"user": "User",
		"source": "Source",
		"category": "Category",
		"description": "Description",
		"comment": "Comment"
	},
	"ReportingPage": {
		"title": "Exporting data",
		"fileType": "File type",
		"fileTypePDF": "PDF",
		"fileTypeCSV": "CSV",
		"pdfOption": "PDF options",
		"pdfOptionCharts": "Include graphics",
		"pdfOptionPreview": "Preview file",
		"more": "Data to be included in the report",
		"moreSettings": "Device configuration",
		"moreTable": "Tables of values",
		"moreAlarm": "Alarm Log",
		"moreLogevents": "Event Diary",
		"export": "Export",
		"period": "Period to export",
		"next": "Next>",
		"moreStats": "Statistical tables",
		"previous": "<Previous"
	},
	"ChannelItem": {
		"channel": "channel",
		"channelInternal": "internal"
	},
	"ModalMessage": {
		"httpForbiddenTitle": "Access denied",
		"httpForbiddenBody": "You do not have the necessary permissions to access this feature. "
	},
	"Tooltip": {
		"DEVICE_DISCONNECTED": "CTS-RF Software does not appear to be connected to CLOUD",
		"WS_SITE_UNLOAD_SLAVE_START": "Unloading ...",
		"WS_SITE_UNLOAD_SLAVE_SUCCESS": "Successfully unloaded",
		"WS_SITE_UNLOAD_SLAVE_ERROR_408": "Unable to download: the software does not seem to be connected to CLOUD",
		"WS_SITE_ALARM_ACK_START": "Acknowledging alarms ...",
		"WS_SITE_ALARM_ACK_ERROR_408": "Acknowledgment of the alarms impossible: the software does not seem connected to the CLOUD",
		"WS_SITE_ALARM_ACK_SUCCESS": "Acknowledging alarms successfully completed",
		"LICENSE_EXPIRATION_DAYS": "Warning your license expires in {1} days"
	},
	"ReportingSlaveList": {
		"title": "Exporting data - Choosing devices to export"
	},
	"LicenseDetail": {
		"activationType": "Subscription type",
		"level": "Subscription level",
		"expirationDate": "Expiration date",
		"licenseCode": "Subscription code",
		"licenceFeature": "Characteristics of the subscription",
		"duration": "Duration of commitment",
		"maxReadData": "Data consultation",
		"maxBackupData": "Backing up data",
		"maxUsers": "Number of users",
		"maxDevices": "Number of recorders",
		"LICENSE_KEY_MC1": "Level 1",
		"LICENSE_KEY_MC2": "Level 2",
		"LICENSE_KEY_MC3": "Level 3",
		"LICENSE_KEY_MEDIFROIDCLOUDFREE": "Level 4",
		"max": "max.",
		"month": "month",
		"slidingMonth": "rolling months",
		"LICENSE_KEY_MC4": "Level 4",
		"renew": "Edit/Renew"
	},
	"ConfigurePage": {
		"storeAsModel": "Save the configuration as a template",
		"unit": "Unit",
		"loraNetwork": "Lora Network",
		"configureDevice": "Configuration",
		"configureSuccess": "Configuration successful",
		"estimatedBatteryLife": "Estimated autonomy",
		"dateHourStart": "Date and Time of start",
		"configureServer": "Configuration sent to the server",
		"configureError": "Configuration error",
		"configureChannels": "Channel configuration",
		"informationDevice": "Device",
		"Designation": "Name",
		"IntervalMesure": "Measurement interval",
		"Intervals": "intervals",
		"IntervalEnregistrement": "Recording interval",
		"DepartType_0": "By date",
		"DepartType": "Start type",
		"DepartType_1": "Button",
		"DepartType_2": "Immediate",
		"DateEtHeureDepart": "Start Date",
		"Enregistrement": "Recording",
		"Display": "Display",
		"Infos": "Device Information",
		"Activated": "Enabled",
		"Leds": "LEDs",
		"Fonctionnement": "Operation",
		"Proteged": "Protected",
		"ConfigurationAllreadyProgramed": "A configuration is already in progress",
		"seuilEntre": "Threshold between {0} and {1} {2}",
		"tempo": "timeout",
		"dataset": "Campaign",
		"comments": "comments",
		"record": "Record",
		"recordMode": "Registration mode",
		"recordMode_1": "Instantly",
		"recordMode_3": "Maximum",
		"recordMode_2": "Minimum",
		"recordMode_4": "Average",
		"stopByButton": "Stop by button",
		"hours": "Hour (s)",
		"minutes": "Minutes)",
		"seconds": "Second (s)",
		"enableThresholds": "Activate thresholds",
		"low": "Low",
		"high": "High",
		"ERROR_417": "Error 417 unknown",
		"ERROR_430": "A configuration is already in progress",
		"ERROR_408": "Impossible configuration: KILOG does not seem connected to CLOUD",
		"ERROR_512": "Error 512 unknown",
		"ERROR_500": "Error 500 unknown",
		"ERROR_220": "Error 220 unknown",
		"success": "Configuration sent successfully",
		"loadConfiguration": "Load a configuration",
		"thresholds": "Alarm thresholds",
		"serial": "Serial number",
		"version": "Version",
		"validmultihelp": "Send this configuration to a selection of compatible devices from this site",
		"validmulti": "Multiple configuration",
		"INVALID_DATE_TIME": "Invalid date format: DD/MM/YYYY HH:MM",
		"cfr21dialogTitle": "Identification and justification",
		"cfr21dialogPasswordLabel": "Your password",
		"cfr21dialogCommentLabel": "The justification for this configuration change",
		"cfr21dialogerror_fields": "All fields must be filled in.",
		"templatedialogTitle": "Select a configuration template",
		"templatedialogDesc": "Please select a configuration template below. ",
		"templatedialogerror_fields": "No configuration has been selected.",
		"INVALID_CONFIG_FORMAT": "Invalid configuration, cancellation",
		"NO_MODE": "No display mode defined",
		"NO_RECORD_TYPE": "No record type defined.",
		"NO_START_TYPE": "No start type defined",
		"NO_CANAL_CONFIG": "No configuration channel defined",
		"NO_RECORD_TIME": "Recording time undefined",
		"NO_CAMPAGNE_NAME": "No defined campaign name",
		"INVALID_CANAL": "Invalid configuration channel",
		"templatedialogLabel": "List of configurations compatible with your device",
		"NO_MESURE_TIME": "Measurement time undefined",
		"cfr21dialogDesc": "Please identify yourself before proceeding with the configuration change",
		"INVALID_MODE": "Invalid display mode",
		"INVALID_LED_ALARM": "No LED mode for defined alarms.",
		"INVALID_LED_ON": "No LED mode for the active indicator of de fi ned",
		"INVALID_CAMPAGNE_NAME_LENGTH": "Campaign name must be at least 3 characters and at most 20",
		"INVALID_RECORD_TIME": "Invalid recording time",
		"INVALID_MESURE_TIME": "Invalid measurement time: must be between ...",
		"INVALID_RECORD_TYPE": "Invalid measurement recording type.",
		"INVALID_START_TYPE": "the type of departure must be by date, button or immediate",
		"INVALID_DATE_FORMAT": "Invalid departure date format",
		"INVALID_SEUIL_FORMAT": "Invalid threshold format: must be a strictly positive number",
		"INVALID_TEMPO_FORMAT": "Invalid timing format: must be a strictly positive number.",
		"INVALID_CHANNEL_NAME": "Invalid channel name: must be a maximum of 15 characters",
		"INVALID_CHANNEL_NUMBER": "Invalid lane number",
		"INVALID_CHANNEL_REF_PROBE": "Unknown probe type",
		"XML_CONFIG_NO_TOKEN": "No definition token for xml configuration",
		"RECORD_LT_MESURE": "The recording time can not be shorter than the measurement time",
		"NO_DATE_GIVEN": "No departure date for the campaign has been entered",
		"INVALID_NO_CHANNEL": "No channels of interest for the recordings",
		"INVALID_SEUILS_VALUES": "The HIGH threshold can not be greater than the BAS threshold",
		"CONFIG_NOT_LOGGED": "Not loggin!",
		"NO_CFR_DATAS": "No credentials were provided",
		"CONFIG_UNKNOWN_USER": "The credentials information provided is erroneous.",
		"INVALID_CHANNEL_UNIT": "Unit of the unknown way",
		"unknown": "Unknown server error ..."
	},
	"SlaveConfiguration": {
		"LaunchFull": "Start the complete reconfiguration by XML",
		"full": "Complete configuration",
		"warningText2": "You can also follow the instructions of this wizard to configure your device by XML file",
		"simplified": "Simplified configuration",
		"warningText1": "Warning ! "
	},
	"ProbesType": {
		"Probe_1": "Room NTC temperature",
		"Probe_3": "NTC temperature dropped",
		"Probe_4": "Current 0-20mA",
		"Probe_5": "4-20mA current",
		"Probe_6": "0-10V voltage",
		"Probe_9": "Thermo-Hygro SHT released",
		"Probe_2": "Internal CTN temperature",
		"Probe_10": "Light",
		"Probe_7": "0-2500mV voltage",
		"Probe_11": "K Thermocouple temperature",
		"Probe_14": "PT100 Temperatures",
		"Probe_8": "Thermo-Hygro SHT Ambience",
		"Probe_15": "Thermo-Hygro Ambient",
		"Probe_17": "Clamp ammeter 20A",
		"Probe_18": "50A Ampere Clamp",
		"Probe_19": "Clamp ammeter 100A",
		"Probe_20": "Clamp ammeter 200A",
		"Probe_13": "Thermocouple Temperature J",
		"Probe_21": "Clamp ammeter 600A",
		"Probe_22": "Thermo-Hygro plastic spilled",
		"Probe_12": "Thermocouple temperature T",
		"Probe_23": "KT20 Temperatures",
		"Probe_16": "Thermo-Hygro stainless steel",
		"Probe_25": "Pulse detection",
		"Probe_26": "Pulse counter",
		"Probe_27": "1000Pa pressure",
		"Probe_28": "Pressure 10000Pa",
		"Probe_29": "CO2 cell",
		"Probe_30": "Light",
		"Probe_lora_2": "Thermocouple J",
		"Probe_lora_1": "Thermocouple K",
		"Probe_lora_3": "Thermocouple T",
		"Probe_lora_4": "Thermocouple N",
		"Probe_24": "Thermocouple temperature S",
		"Probe_lora_5": "Thermocouple S",
		"Probe_lora_6": "Current 0-20mA",
		"Probe_lora_7": "4-20mA current",
		"Probe_lora_8": "0-5V voltage",
		"Probe_lora_9": "0-10V voltage",
		"Probe_lora_11": "50A Ampere Clamp",
		"Probe_lora_10": "Impulse counter",
		"Probe_lora_12": "Clamp ammeter 100A",
		"Probe_lora_13": "Clamp ammeter 200A",
		"Probe_lora_14": "Clamp ammeter 600A",
		"Probe_lora_17": "Internal temperature",
		"Probe_lora_15": "External NTC temperature",
		"Probe_lora_18": "Water pressure 0-10 bar",
		"Probe_lora_16": "external PT100 temperature",
		"Probe_lora_19": "Hygro-temperature probe",
		"Probe_lora_21": "ABS hygro-temperature probe/amb",
		"Probe_lora_20": "Stainless steel hygro-temperature probe",
		"Probe_lora_22": "Internal hygro-temperature probe",
		"Probe_lora_23": "Internal light",
		"Probe_lora_24": "Internal CO2",
		"Probe_lora_26": "Internal pressure 1000 Pa",
		"Probe_lora_28": "Water pressure 0-20 bar",
		"Probe_lora_27": "Internal pressure 10000 Pa",
		"Probe_lora_25": "Internal atmospheric pressure"
	},
	"AssistantConfiguration": {
		"page1Description2": "This information is located at the back of the recorder box.",
		"deviceSerial": "Serial number",
		"deviceCode": "Device code",
		"deviceIdentication": "Device identification",
		"configurationOption2": "Configuration by XML file",
		"deviceConfiguration": "Device configuration",
		"configurationOption1": "Configuration by mobile application (Recommended)",
		"page2Option2Description2": "A configuration code will appear on the screen of the recorder, fill in the here.",
		"page1Description1": "Enter the serial number and the code of the device.",
		"page2Option2Warning": "Warning ! ",
		"page2Option1Info1": "In order to continue getting started with your device, we recommend using the Medifroid Cloud mobile application. ",
		"configurationCode": "Configuration code",
		"page2Option2Description1": "Connect your device in USB to the computer.",
		"page4Description2": "Copy this file to your recorder, displayed on your computer in removable storage.",
		"page4Title": "Saving the configuration",
		"designation": "Detail © shipping name",
		"page2Option1Info2": "You can also follow the instructions in this wizard to configure your device by XML file.",
		"page4Description1": "The configuration file conf {token} .xml has been saved on your computer.",
		"page4Warning": "Warning ! ",
		"page5Description": "Once the configuration file is copied to your device, it is ready to work. "
	}
}