'use strict';


module.exports = {

  
  COMMON: {
    // pour les noms des voies //////////////////////////////
    channel_1647331140_1: 'Interne', // KP Tracklog: 1 seule voie

    channel_1647363012_1: '1', // KTT: 4 voies internes
    channel_1647363012_2: '2',
    channel_1647363012_3: '3',
    channel_1647363012_4: '4',

    channel_1647560644_1: 'Interne 1', // KCC: 4 voies internes
    channel_1647560644_2: 'Interne 2',
    channel_1647560644_3: 'Interne 3',
    channel_1647560644_4: 'Interne 4',

    channel_1647542564_1: 'Interne', // KT: 5 voies
    channel_1647542564_2: '1',
    channel_1647542564_3: '2',
    channel_1647542564_4: '3',
    channel_1647542564_5: '4',


    channel_1648328996_1: 'Interne', //CTS CLOUD: 5 voies
    channel_1648328996_2: '1-CTS',
    channel_1648328996_3: '2-CTS',
    channel_1648328996_4: '3-CTS',
    channel_1648328996_5: '4-CTS',
    /////////////////////////////////////////////////////////
    //
    mailNotificationTitle: 'Gestion des alertes',
    mailNotification: 'Alertes par mail',
    mailNotificationThreshold: 'Recevoir les alarmes sur seuils',
    mailNotificationTechnical: 'Recevoir les alarmes techniques',
    passwordStrategyTitle: 'Gestion de la stratégie des mots de passe',
    passwordStrategyLabel: 'Durée de validité des mots de passe',
    passwordStrategyDescription: 'Nombre de jours maximal de validité des mots de passes sur vos différents sites (en nombre de jours).',
    passwordStrategyPlaceholder: 'Par défaut, 90 jours de validité',
    passwordStrategyUnit: 'Jour(s)',
    LORA_DEVICE_NOT_FOUND: 'L\'appareil n\'existe pas',
    LORA_DEVICE_ALREADY_REGISTERED: 'L\'appareil est déjà enregistré',
    LORA_DEVICE_SITE_NOT_FOUND: 'Le site est introuvable',
    selectAll: 'Tout sélectionner',
    unselectAll: 'Tout désélectionner',
    defaultZoneName: 'Zone par défaut',
    all: 'Tous',
    all_female: 'Toutes',
    cancel: 'Annuler',
    ok: 'OK',
    valid: 'Valider',
    send: 'Envoyer',
    add: 'Ajouter',
    save: 'Enregistrer',
    delete: 'Supprimer',
    date: 'Date',
    hour: 'Heure',
    channel: 'Voie',
    channelInternal: 'interne',
    unit_unknown: 'Unité non spécifiée',
    errorFieldsMandatory: 'Veuillez renseigner tous les champs',
    errorConfirmationMismatch: 'La confirmation du mot de passe ne correspond pas',
    errorMaxProfile: 'Nombre maximum de profils atteint',
    errorNameExists: 'Le nom de profil n\'est pas disponible',
    USER_EXISTS: 'Le nom d\'utilisateur n\'est pas disponible',
    MAIL_EXISTS: 'L\'adresse mail n\'est pas disponible',
    USER_OR_MAIL_EXISTS: 'Le nom d\'utilisateur ou le mail ne sont pas disponibles',
    LICENSE_CODE_INVALID: 'Le code abonnement est invalide',
    LICENSE_USED: 'Le code abonnement a déjà été utilisé',
    LICENSE_MAX_USERS: 'Vous avez atteint la limite du nombre d\'utilisateurs actifs',
    LICENSE_MAX_READ_DATA: 'Vous ne pouvez consulter les données que sur une période de {1} mois glissants',
    LICENSE_MAX_SLAVES: 'Vous avez atteint la limite du nombre d\'appareils actifs',
    LICENSE_KEY_INVALID: 'Le code produit est invalide',
    MASTER_NOT_FOUND: 'La license est introuvable',
    SITE_EXISTS: 'Le site est déjà enregistré sur un autre compte',
    login: 'Identifiant de connexion',
    lastName: 'Nom',
    firstName: 'Prénom',
    mail: 'Adresse mail',
    password: 'Mot de passe',
    confirmation: 'Confirmation',
    name: 'Nom',
    unit_0: 'aucune',
    unit_1: 'm/s',
    unit_2: 'fpm',
    unit_3: 'm3/h',
    unit_4: 'L/s',
    unit_5: 'cfm',
    unit_6: 'm3/s',
    unit_7: '°C',
    unit_8: '°F',
    unit_9: '%RH',
    unit_10: '%PSI',
    unit_11: 'Pa',
    unit_12: 'mmH2O',
    unit_13: 'inWg',
    unit_14: 'kPa',
    unit_15: 'mmHg',
    unit_16: 'mbar',
    unit_17: 'absolueg/kg',
    unit_18: '°C Td',
    unit_19: '°F Td',
    unit_20: '°C Tw',
    unit_21: '°F Tw',
    unit_22: 'kJ/kg',
    unit_23: 'mA',
    unit_24: 'A',
    unit_25: 'mV',
    unit_26: 'V',
    unit_27: 'lux',
    unit_31: 'unité libre',
    unit_32: 'pulse',
    unit_33: 'pulses',
    unit_34: 'KelvinK',
    unit_35: 'km/h',
    unit_36: 'mph',
    unit_37: 'Hz',
    unit_38: 'tr/min',
    unit_39: 'rpm',
    unit_40: 'm/min',
    unit_41: 'in/min',
    unit_42: 'bar',
    unit_43: 'daPa',
    unit_44: 'hPa',
    unit_45: 'ppm',
    unit_46: 'dB',
    unit_47: 'ohms',
    unit_lora_0: 'aucune',
    unit_lora_1: '%RH',
    unit_lora_2: '',
    unit_lora_3: 'unité libre',
    unit_lora_15: 'unité inconnue',

    unit_lora_16: '°C',
    unit_lora_17: '°F',
    unit_lora_18: 'K',
    unit_lora_19: 'Delta °C',
    unit_lora_20: 'Delta °F',

    unit_lora_32: '%RH',
    unit_lora_33: 'g/kg',
    unit_lora_34: 'kJ/kg',
    unit_lora_35: '°CTd',
    unit_lora_36: '°FTd',
    unit_lora_37: '°C Tw',
    unit_lora_38: '°F Tw',
    unit_lora_39: 'g/m3',

    unit_lora_48: 'bar',
    unit_lora_49: 'PSI',
    unit_lora_50: 'kPa',
    unit_lora_51: 'inWg',
    unit_lora_52: 'hPa',
    unit_lora_53: 'mbar',
    unit_lora_54: 'mmHg',
    unit_lora_55: 'mmH2O',
    unit_lora_56: 'daPa',
    unit_lora_57: 'Pa',

    unit_lora_64: 'm/s',
    unit_lora_65: 'fpm',
    unit_lora_66: 'km/h',
    unit_lora_67: 'mph',

    unit_lora_80: 'm3/h',
    unit_lora_81: 'l/s',
    unit_lora_82: 'cfm',
    unit_lora_83: 'm3/s',
    unit_lora_84: 'nm3/h',
    unit_lora_85: 'dm3/h',

    unit_lora_96: 'Hz',
    unit_lora_97: 'tr/min',
    unit_lora_98: 'rpm',
    unit_lora_99: 'm/min',
    unit_lora_100: 'in/min',
    unit_lora_101: 'ft/min',
    unit_lora_102: 'm/s',

    unit_lora_112: 'ppm',
    unit_lora_113: 'mg/m3',
    unit_lora_114: 'mg/kWh',
    unit_lora_115: 'g/kWh',
    unit_lora_116: 'g/GJ',
    unit_lora_117: 'g/m3',
    unit_lora_118: '%',
    unit_lora_119: '% LIE',
    unit_lora_120: 'g/an',

    unit_lora_128: 'lux',
    unit_lora_129: 'fc',
    unit_lora_130: 'W/m2',
    unit_lora_131: 'klux',
    unit_lora_132: 'kfc',

    unit_lora_144: 'db',

    unit_lora_160: 'mV',
    unit_lora_161: 'V',
    unit_lora_162: 'µA',
    unit_lora_163: 'mA',
    unit_lora_164: 'A',
    unit_lora_165: 'Ohms',

    unit_lora_176: 'wbgt',
    unit_lora_177: 'W/m2/K',

    unit_lora_192: 's',
    unit_lora_193: 'min',
    unit_lora_194: 'h',

    unit_lora_208: 'mm',
    unit_lora_209: 'in',
    unit_lora_210: 'm',

    unit_lora_255: 'Comptage',
    source_0: 'Application',
    source_1: 'Appareil',
    source_2: 'Alarme Deportée',
    source_3: 'Voie Calculée',
    source_4: 'Base De Communication',
    source_5: 'Cloud',
    code_1: 'Application Lancée',
    code_2: 'Application Fermée',
    code_3: 'Modification Préférences',
    code_4: 'Modification Paramètres Messagerie',
    code_10: 'Connexion Utilisateur',
    code_11: 'Deconnexion Utilisateur',
    code_12: 'Connexion Echouée',
    code_13: 'Ajout Utilisateur',
    code_14: 'Modification Utilisateur',
    code_15: 'Suppression Utilisateur',
    code_16: 'Changement Password',
    code_17: 'Ajout Groupe',
    code_18: 'Modification Groupe',
    code_19: 'Suppression Groupe',
    code_20: 'Gestion Utilisateurs Modifiée',
    code_100: 'Appairage Appareil RF',
    code_101: 'Suppression Appareil RF',
    code_102: 'Remplacement Appareil RF',
    code_103: 'Placement Appareil RF',
    code_104: 'Retrait Appareil RF',
    code_105: 'Griser Appareil RF',
    code_106: 'Degriser Appareil RF',
    code_107: 'Configuration Verification Reseau',
    code_108: 'Planification Vidages',
    code_109: 'Planification Mesures',
    code_201: 'Configuration Appareil',
    code_202: 'Dechargement Appareil',
    code_203: 'Lancement Campagne Par PC',
    code_204: 'Arrêt Campagne Par PC',
    code_205: 'Vidage Appareil',
    code_206: 'Lecture Mesures Appareil',
    code_207: 'Test Communication',
    code_1001: 'Produit Ajouté',
    code_1002: 'Infos Produit Modifiées',
    code_1003: 'Produit Supprime',
    code_2001: 'Alarme Deportée Ajoutée',
    code_2002: 'Alarme Deportée Modifiée',
    code_2003: 'Alarme Deportée Supprimée',
    code_2004: 'Pilotage Relais Appareil',
    code_2005: 'Alarme Email Ajoutée',
    code_2006: 'Alarme Email Modifiée',
    code_2007: 'Alarme Email Supprimée',
    code_2008: 'Alarme Email Envoyée',
    code_3001: 'Démarrage Service',
    code_3002: 'Arrêt Service',
    code_5001: 'Connexion échouée',
    code_5002: 'Connexion rétablie',
    code_5003: 'Echec envoi de données',
    code_5004: 'Requête au serveur',

    code_6001: 'Création de site',
    code_6002: 'Supression de site',
    code_6003: 'Echec identification',

    code_2010: 'Configuration Appareil Simplifiée',
    code_2011: 'Configuration Appareil Bluetooth',
    code_2012: 'Configuration Appareil Complète',

    probe_1: 'Température CTN Ambiance',
    probe_2: 'Température CTN Interne',
    probe_3: 'Température CTN Déportée',
    probe_4: 'Courant 0/20 mA',
    probe_5: 'Courant 4/20 mA',
    probe_6: 'Tension 0/10 V',
    probe_7: 'Tension 0/2500 mV',
    probe_8: 'Thermo-Hygro SHT Ambiance',
    probe_9: 'Thermo-Hygro SHT Déportée',
    probe_10: 'Luminosité',
    probe_11: 'Température Thermocouple K',
    probe_12: 'Température Thermocouple T',
    probe_13: 'Température Thermocouple J',
    probe_14: 'Température PT100 Déportée',
    probe_15: 'Thermo-Hygro Ambiance',
    probe_16: 'Thermo-Hygro Inox Déportée',
    probe_17: 'Pince ampèremétrique 20 A',
    probe_18: 'Pince ampèremétrique 50 A',
    probe_19: 'Pince ampèremétrique 100 A',
    probe_20: 'Pince ampèremétrique 200 A',
    probe_21: 'Pince ampèremétrique 600 A',
    probe_22: 'Thermo-Hygro Plastique Déportée',
    probe_23: 'Température KT20',
    probe_24: 'Température Thermocouple S',
    probe_25: 'Détection impulsions',
    probe_26: 'Compteur impulsions',
    probe_27: 'Pression 1000 Pa',
    probe_28: 'Pression 10000 Pa',
    Probe_29: 'Cellule CO2',
    Probe_30: 'Lumière',
    Probe_lora_1: 'Thermocouple K',
    Probe_lora_2: 'Thermocouple J',
    Probe_lora_3: 'Thermocouple T',
    Probe_lora_4: 'Thermocouple N',
    Probe_lora_5: 'Thermocouple S',
    Probe_lora_6: 'Courant 0-20mA',
    Probe_lora_7: 'Courant 4-20mA',
    Probe_lora_8: 'Tension 0-5V',
    Probe_lora_9: 'Tension 0-10V',
    Probe_lora_10: 'Compteur impulsion',
    Probe_lora_11: 'Pince ampèremétrique 50A',
    Probe_lora_12: 'Pince ampèremétrique 100A',
    Probe_lora_13: 'Pince ampèremétrique 200A',
    Probe_lora_14: 'Pince ampèremétrique 600A',
    Probe_lora_15: 'Température CTN externe',
    Probe_lora_16: 'température PT100 externe',
    Probe_lora_17: 'Température interne',
    Probe_lora_18: 'Pression d\'eau 0-10 bar',
    Probe_lora_19: 'Sonde hygro-température',
    Probe_lora_20: 'Sonde hygro-température inox',
    Probe_lora_21: 'Sonde hygro-température ABS/amb',
    Probe_lora_22: 'Sonde hygro-température interne',
    Probe_lora_23: 'Lumière interne',
    Probe_lora_24: 'CO2 interne',
    Probe_lora_25: 'Pression atmosphérique interne',
    Probe_lora_26: 'Pression interne 1000 Pa',
    Probe_lora_27: 'Pression interne 10000 Pa',
    Probe_lora_28: 'Pression d\'eau 0-20 bar',
    techAlarm_1: 'Batterie changée',
    techAlarm_2: 'Batterie faible',
    techAlarm_3: 'Perte de communication',
    techAlarm_3_more: 'Aucune communication avec le serveur depuis 1heure',
    techAlarm_4: 'Communication rétablie',
    techAlarm_666: 'Erreur de traitement de données',
    techAlarm_510: 'Erreur de traitement de données.',
    techAlarm_510_more: '510: Pas de réponse de la base de données',
    techAlarm_511: 'Erreur de traitement de données.',
    techAlarm_511_more: '511: Version de configuration inconnu.',
    techAlarm_512: 'Erreur de traitement de données.',
    techAlarm_512_more: '512: Appareil non configuré',
    techAlarm_506: 'Erreur de traitement de données.',
    techAlarm_506_more: '506: Configuration de l\'appareil et données reçues incohérentes',
    techAlarm_514: 'Erreur de traitement de données.',
    techAlarm_514_more: '514: Erreur de base de données.',
    not_configurable: "**Vous ne pouvez pas configurer cette voie.",
    record_as_template:"Enregistrer la configuration comme modèle",
    error_template_name_empty:'Vous devez renseigner un nom de modèle.',
    
    'Request Timeout':'Le serveur a mis trop de temps a répondre, merci de rééssayer dans quelques instants.',
    INVALID_PASSWORD_LENGTH: 'Le mot de passe doit faire au moins 6 caractères.',
    ALREADY_USED_PASSWORD: 'Vous avez déjà utilisé récemment ce mot de passe, merci d\'en choisir un autre.'
  },
  LostPasswordForm: {
    mail: 'Adresse email',
    errorWrongMail: 'Adresse mail incorrecte',   
    errorInactive: '**Ce compte est actuellement inactif. Veuillez contacter votre administrateur.',
    title: 'Identifiant ou mot de passe oublié'
  },
  InstallationTypeChoice: {
    siteName: 'Nom du site',
    siteSerial: 'Identifiant de l\'installation',
    slaveSerial: 'N° de série de l\'appareil',
    slaveCode: 'Code de l\'appareil',

    devicetype_placeholder: '**Choisir le type d\'appareil',
    
    modal_info_title: '**Installation CTS-Cloud',
    modal_info_txt1: '**Veuillez entrer les références d\'un de vos appareils CTS-Cloud.',
    modal_info_txt2: '**Le numéro de série et le code appareil se trouvent sur l\'étiquette située à l\'arrière du boîtier.',
    modal_info_code: '**Code appareil',
    modal_info_serial: '**Numéro de série',
    modal_info_ok: '**OK'

  },
  RegisterForm: {
    login: 'Identifiant de connexion',
    register: 'S\'enregistrer',
    mail: 'Mail',
    licenseCode: 'Code abonnement',
    confirmation: 'Confirmation du mot de passe',
    personalInformations: 'Informations Personnelles',
    accountInformations: 'Paramètres du compte',
    siteInformations: 'Informations du site'
  },
  LoginForm: {
    ERROR: 'Une erreur est survenue lors de la connexion. Veuillez contacter votre administrateur.',
    USER_INACTIVE: 'Votre accès est désactivé. Veuillez contacter votre administrateur.',
    connexion: 'Connexion',
    title: 'Connexion',
    register: 'Créer un compte',
    errorFieldsMandatory: 'Tous les champs sont obligatoire',
    errorWrongLogin: 'Identifiant ou mot de passe incorrect',
    account_tmp_blocked: 'Ce compte a été bloqué suite à une tentative d\'intrusion pour des raisons de sécurité.',
    admin_account_tmp_blocked:'Ce compte a été bloqué suite à une tentative d\'intrusion. Un mail a été envoyé à l\'administrateur du site',
    attempt_reach_limit: 'Vous avez atteind le nombre maximal d\'essais pour vous identifier.',
    activationError: 'Une erreur est survenue durant l\'activation',
    activationSuccess: 'Votre compte est maintenant activé. Vous pouvez vous connecter.',
    registerSuccess: 'Votre inscription a bien été prise en compte',
    lostPasswordSuccess: 'Un email contenant votre nouveau mot de passe a été envoyé à l\'adresse',
    lostPassword: 'Identifiant ou mot de passe oublié',
    cfr21_password_success: 'Vos informations de connexion ont été mises à jour.'
  },
  Menu: {
    events: 'Journal des événements',
    admin_events:'Journal d\'administration',
    reporting: 'Exporter',
    unload: 'Déchargement',
    informations: 'Informations',
    settings: 'Paramètres',
    logoff: 'Déconnexion',
    configuration: 'Configuration',
    configure: 'Configuration',
  },
  SiteList: {},
  SiteItem: {},
  SlaveItem: {},
  SettingsPage: {
    settings: 'Paramètres'
  },
  InformationsPage: {
    informations: 'Informations',
    version: 'Version',
    documentation: 'Notice',
    documentationLink: 'Télécharger la notice'
  },
  SettingsUserAccessPage: {
    title: 'Gestion des accès utilisateurs'
  },
  SettingsAccountPage: {
    title: 'Mon Compte'
  },
  SettingsLicensePage: {
    title: 'Abonnement',
    renewLicenseTitle: 'Abonnement',
    renewLicenseSubtitle: 'Veuillez rentrer votre nouveau code d\'abonnement',
    licenseCode: 'Code d\'abonnement',
    licenseRenewSuccess: 'Votre nouvel abonnement est maintenant actif'
  },
  SettingsUserPage: {
    title: 'Gestion des utilisateurs',
    addUserTitle: 'Ajout d\'un utilisateur',
    addUserSubtitle: 'Veuillez renseigner les champs suivants',
    login: 'Identifiant de connexion',
    ERROR_INVALID_PASSWRD: "Un mot de passe doit faire un minimum de 6 caractères",
    ERROR_INVALID_LOGIN:"Un login doit faire un minimum de 6 caractères"
  },
  SettingsProfilePage: {
    title: 'Gestion des profils',
    addProfileTitle: 'Ajout d\'un profil',
    addProfileSubtitle: 'Veuillez renseigner les champs suivants'
  },
  UserList: {
    login: 'Utilisateurs',
    role: 'Groupe',
    userSelection: 'Sélection d\'un utilisateur'
  },
  ProfileList: {
    profiles: 'Profils',
    profileSelection: 'Sélection d\'un profil'
  },
  UserDetail: {
    informations: 'Information du compte',
    active: 'Compte actif',
    defaultProfile: 'Profil par défaut',
    sites: 'Sites accessibles',
    accesses: 'Accès',
    defaultZone: 'Zone non définie',
    MODIFY_SUCCESS: 'Utilisateur modifié avec succés',
    DELETE_SUCCESS: 'Utilisateur supprimé avec succés',
    ADD_SUCCESS: 'Utilisateur ajouté avec succés',
    confirmDelete: 'Etes-vous sûr de vouloir supprimer cet utilisateur ?',
    updatePassword: 'Modifier le mot de passe',
    updatePasswordTitle: 'Modification du mot de passe',
    errorInvalidPassword: "Un mot de passe doit faire un minimum de 6 caractères",
    errorInvalidLogin:"Un mot de passe doit faire un minimum de 6 caractères",
    
  },
  AccountDetail: {
    informations: 'Information du compte',
    mail: 'Adresse mail',
    UPDATE_SUCCESS: 'Utilisateur modifié avec succés',
    updatePassword: 'Modifier le mot de passe',
    updatePasswordTitle: 'Modification du mot de passe',
  },
  ProfileDetail: {
    informations: 'Information du profil',
    active: 'Profil actif',
    sites: 'Sites accessibles',
    accessType: 'Type d\'accès',
    confirmDelete: 'Etes-vous sûr de vouloir supprimer ce profil ?',
    aclAffectation: 'Affectation des droits',
    global: 'Général',
    MODIFY_SUCCESS: 'Profile modifié avec succés',
    DELETE_SUCCESS: 'Profile supprimé avec succés',
    ADD_SUCCESS: 'Profile ajouté avec succés',
    API_ADMIN_MANAGE: 'Gestion des droits',
    API_ADMIN_MANAGE_PROFILES: 'Gestion des profils',
    API_ADMIN_MANAGE_USERS: 'Gestion des utilisateurs',
    API_USERS_ADD_SITES: 'Ajout',
    API_ALARMS_UPDATE: 'Acquittement des alarmes',
    API_SITES_MANAGE_SLAVES: 'Gestion des appareils',
    API_SITES_UPDATE_SLAVES: 'Activation/Désactivation',
    API_SITES_CONFIGURE_SLAVES: 'Configuration des appareils',
    API_USERS_MANAGE_SITES: 'Gestion des sites',
    API_USERS_UPDATE_SITES: 'Modification du nom',
    API_SITES_MANAGE_ZONES: 'Gestion des zones / groupements d\'appareils',
    API_USER_CFR31: 'Signature des données',
    PROFILE_USED: 'Vous ne pouvez pas supprimer un profil attaché à un utlisateur'
  },
  UserAccessList: {
    login: 'Utilisateur',
    success: 'Enregistrement effectué avec succés'
  },
  SettingsSideBar: {
    settings: 'Paramètres',
    users: 'Utilisateurs',
    profiles: 'Profils',
    license: 'Abonnement',
    groups: 'Groupes',
    userAccesses: 'Accès utilisateurs',
    account: 'Mon Compte'
  },
  AdminPage: {
    userList: 'Liste des utilisateurs sur lesquels vous pouvez prendre le contrôle',
    site: 'Nom du site',
    master: 'Numéro de série',
    activated: 'Compte activé',
    yes: 'Oui',
    no: 'Non',
    search: 'Recherche',
  },
  SitePage: {
    siteList: 'Liste de vos sites',
    welcome: 'Bienvenue sur Kimo Cloud',
    helpAddSite: 'Ajoutez vos sites en cliquant sur l’icône (+) pour accéder aux données de vos appareils.',
    addSiteTitle: 'Ajout d\'un site',
    addSiteSubtitle: 'Veuillez indiquer les informations du site à ajouter',
    serial: 'Identifiant du site',
    siteName: 'Nom du site',
    MASTER_NOT_FOUND: 'La license est introuvable',
    CONTROL_EXISTS: 'Le site est déjà enregistré sur un autre compte'
  },
  HomePage: {
    confirmDelete: 'Etes-vous sûr de vouloir supprimer ce site ?',
    waitingZoneName: 'Appareils en attente de configuration',
    unload: 'Déchargement forcé',
    ZONE_DEFAULT: 'Vous ne pouvez pas modifier la zone par défaut',
    editZoneTitle: 'Editer la zone',
    addZoneTitle: 'Ajouter une zone',
    zoneName: 'Nom de la zone',
    addZone: 'Ajouter une zone',
    editZone: 'Editer une zone',
    editSite: 'Modification du site',
    siteName: 'Nom du site',
    confirmZoneDelete: 'Etes-vous sûr de vouloir supprimer cette zone ?',
    confirmChangeSlaveStatus: 'Attention :  les mesures et les alarmes de cet appareil ne seront plus envoyées sur le cloud si vous le désactivez.\nConfirmer la désactivation de l\'appareil ?'
  },
  NavBar: {
    feedbackTitle: 'Votre avis nous intéresse',
    feedbackSubtitle: 'Veuillez saisir votre avis',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion'
  },
  SideBar: {
    alarm: 'Liste des alarmes',
    slaves: 'Liste des appareils',
  },
  SlaveList: {
    slaves: 'Liste des appareils'
  },
  ChannelList: {
    measures: 'Dernières mesures relevées',
    noMeasures: 'Aucunes mesures relevées',
    values: 'Valeurs',
    statistics: 'Statistiques',
    dataViewMode0: 'Graphique',
    dataViewMode1: 'Tableau',
    dataViewMode2: 'Résumé',
    dataViewMode3: 'Configuration',
    dataViewMode4: 'Signatures',
    minimum: 'Minimum',
    maximum: 'Maximum',
    average: 'Moyenne',
    deviation: 'Ecart type',
    mkt: 'MKT'
  },
  ChannelListTable: {
    values: 'Valeurs',
    statistics: 'Statistiques',
    minimum: 'Minimum',
    maximum: 'Maximum',
    average: 'Moyenne',
    deviation: 'Ecart type',
    mkt: 'MKT'
  },
  SlaveAbstract: {
    comments: 'Commentaire',
    device: 'Appareil',
    configuration: 'Configuration',
    channels: 'Voies',
    reference: 'Appareil',
    designation: 'Désignation',
    serial: 'N° de série',
    version: 'Version',
    campaign: 'Campagne',
    logType: 'Type d\'enregistrement',
    logType_0: 'Différé',
    logType_1: 'Instant',
    logType_2: 'Minimum',
    logType_3: 'Maximum',
    logType_4: 'Moyenne',
    logType_5: 'Surveillance',
    logType_6: 'EnLigne',
    logType_7: 'Fin',
    logType_8: 'Thermometre',
    logType_9: 'Thermohygrometre',
    logType_10: 'Detection d\'impulsions',
    recordDelay: 'Intervalle d\'enregistrement',
    measureInterval: 'Intervalle de mesure',
    startDate: 'Date de départ',
    endDate: 'Date de fin',
    probeType: 'Type de sonde',
    alarmState: 'Etat de la voie',
    alarmState_0: 'Normal',
    alarmState_1: 'Active',
    alarmState_2: 'Inconnu',
    highThreshold: 'Seuil haut',
    lowThreshold: 'Seuil bas',
    minute: 'min.',
    noAlarmState: 'Pas d\'alarmes configurées',
  },
  AlarmList: {
    alarms: 'Alarmes',
    sameComment: 'Appliquer le même commentaire à toutes les alarmes',
    slaveDesignation: 'Désignation de l\'appareil',
    channelDesignation: 'Désignation de la voie',
    value: 'Valeur',
    mode: 'Etat',
    filterUnacked: 'Alarmes non acquittées',
    filterAcked: 'Alarmes acquittées',
    filterNone: 'Toutes les alarmes',
    ack: 'Acquitter',
    ackPending: 'Acquittement en cours...',
    modalTitle: 'Identification et Commentaires',
    modalSubtitle: 'Laissez un message avant d\'acquitter l\'alarme',
    oneAckAlarm: 'Veuillez sélectionner au moins une alarme à acquitter',
    passwordLabel: 'Votre mot de passe',
    passwordDesc: 'Merci de vous identifier avant de procéder a l\'acquittement des alarmes',
    justificationLabel: 'Justification de l\'acquittement',
    justificationDesc: 'La justification est obligatoire',
    error_invalid_fields: 'Tous les champs doivent obligatoirement être renseignés.'
  },
  AlarmItem: {
    CONFIRMED_CONFIGURATION:'Configuration confirmée',
    BLE_STOP_CAMPAGNE:'Arret de campagne via application mobile',
    CAMPAGNE_END:'Arret de campagne',
    CAMPAGNE_STARTED:'Démarrage de la campagne',
    BLE_UNLOAD:'Déchargement de données via application mobile',
    ANNUL_CONFIG:'Annulation de la configuration via application mobile',
    UNKNOWN_DATAS_CONFIGURATION_A:'Erreur de traitement de données.',
    UNKNOWN_DATAS_CONFIGURATION_B: 'Erreur de traitement de données.',
    UNKNOWN_DATAS_CONFIGURATION_C: 'Erreur de traitement de données.',
    INCOHERENT_CHANNELS_COUNT:'Configuration de l\'appareil et données reçues incohérentes'
  },
  DateFilterList: {
    LATEST: 'Dernières données',
    TODAY: 'Aujourd\'hui',
    YESTERDAY: 'Depuis Hier',
    WEEK: '7 derniers jours',
    MONTH: '30 derniers jours',
    INTERVAL: 'Entre deux dates',
    UNACKED: 'Alarmes non acquittées',
    ACKED: 'Alarmes acquittées',
    ALL: 'Toutes les alarmes'
  },
  UnloadList: {
    unload: 'Décharger',
    unloadTitle: 'Déchargement',
    unloadSubtitle: 'Sélectionner les appareils à décharger',
    modalTitle: 'Déchargement en cours',
    modalSubtitle1: 'Cette opération peut durer quelques minutes.',
    modalSubtitle2: 'Vous pouvez continuer à utiliser l\'application pendant la mise à jour des données',
    oneUnload: 'Veuillez sélectionner au moins un appareil'
  },
  LogEventList: {
    events: 'Journal des évènements',
    user: 'Utilisateur',
    source: 'Source',
    category: 'Catégorie',
    description: 'Description',
    comment: 'Commentaire',
    CONFIRMED_CONFIGURATION:'Configuration confirmée',
    BLE_STOP_CAMPAGNE:'Arret de campagne via application mobile',
    CAMPAGNE_END:'Arret de campagne',
    CAMPAGNE_STARTED:'Démarrage de la campagne',
    BLE_UNLOAD:'Déchargement de données via application mobile',
    ANNUL_CONFIG:'Annulation de la configuration via application mobile',
    UNKNOWN_DATAS_CONFIGURATION_A:'Erreur de traitement de données.',
    UNKNOWN_DATAS_CONFIGURATION_B: 'Erreur de traitement de données.',
    UNKNOWN_DATAS_CONFIGURATION_C: 'Erreur de traitement de données.',
    INCOHERENT_CHANNELS_COUNT:'Configuration de l\'appareil et données reçues incohérentes'
  },
  AdminLogEventList: {
    events: 'Journal des évènements - Administration',
    user: 'Utilisateur',
    source: 'Source',
    category: 'Catégorie',
    description: 'Description',
    comment: 'Commentaire',
    errorLoadingLogs: 'Une erreur lors de la récupération des logs. Merci de réssayer plus tard...',
    admin_logs_AUTH_ECHEC: 'Un utilisateur a échoué à se connecter a 4 reprises. Ce compte a été bloqué pour des raisons de sécurité pour 10 mins.',
    admin_logs_USER_CONNECTION: ' ',
    admin_logs_USER_DECONNEXION: ' ',
    admin_logs_SITE_CREATION: 'Création d\'un nouveau site sur le portail web:',
    admin_logs_SITE_DELETION: 'Suppression du site'
  },
  ReportingPage: {
    title: 'Exportation des données',
    fileType: 'Type de fichier',
    fileTypePDF: 'PDF',
    fileTypeCSV: 'CSV',
    pdfOption: 'Options PDF',
    pdfOptionCharts: 'Inclure les graphiques',
    pdfOptionPreview: 'Prévisualiser le fichier',
    more: 'Données à intégrer au rapport',
    moreTable: 'Tableaux de valeurs',
    moreSettings: 'Configuration des appareils',
    moreStats: 'Tableaux de statistiques',
    moreAlarm: 'Journal des alarmes',
    moreLogevents: 'Journal des événements',
    moreSignatures: '**Signatures (cfr21)',
    export: 'Exporter',
    period: 'Période à exporter',
    next: 'Suivant >',
    previous: '< Précédent'
  },
  ChannelItem: {
    channel: 'Voie',
    channelInternal: 'interne',
  },
  Modal: {},
  ModalMessage: {
    httpForbiddenTitle: 'Accès refusé',
    httpForbiddenBody: 'Vous ne disposez pas des autorisations nécessaires pour accéder à cette fonctionnalité. Veuillez contacter votre administrateur.',
    httpErrorTitle: '**Erreur de connexion au serveur',
    httpErrorBody: '**Une erreur de communication avec le serveur est arrivé. Merci de réssayer plus tard.',
    httpSignaturePostError: '**Une erreur est arrivée lors de l\'enregistrement des signatures. Merci de réessayer plus tard.'
  },
  Table: {},
  Tooltip: {
    DEVICE_DISCONNECTED: 'Le Logiciel CTS-RF ne semble pas connecté au CLOUD',
    WS_SITE_UNLOAD_SLAVE_START: 'Déchargement en cours...',
    WS_SITE_UNLOAD_SLAVE_SUCCESS: 'Déchargement effectué avec succés',
    WS_SITE_UNLOAD_SLAVE_ERROR_408: 'Déchargement impossible :  le logiciel ne semble pas connecté au CLOUD',
    WS_SITE_ALARM_ACK_START: 'Acquittement des alarmes en cours...',
    WS_SITE_ALARM_ACK_SUCCESS: 'Acquittement des alarmes effectué avec succés',
    WS_SITE_ALARM_ACK_ERROR_408: 'Acquittement des alarmes impossible : le logiciel ne semble pas connecté au CLOUD',
    WS_SITE_ALARM_ACK_ERROR_403: 'Acquittement des alarmes impossible : Action non autorisée.',
    WS_SITE_ALARM_ACK_ERROR_undefined:'Acquittement des alarmes impossible : Le serveur a rencontré une erreur inconnue',
    LICENSE_EXPIRATION_DAYS: 'Attention votre license arrive à expiration dans {1} jours'
  },
  ReportingSlaveList: {
    title: 'Exportation des données - Choix des appareils à exporter'
  },
  Graph: {},
  LicenseDetail: {
    activationType: 'Type d\'abonnement',
    level: 'Niveau d\'abonnement',
    expirationDate: 'Date d\'expiration',
    licenseCode: 'Code d\'abonnement',
    licenceFeature: 'Caractéristiques de l\'abonnement',
    maxDevices: 'Nombre d\'enregistreurs',
    duration: 'Durée d\'engagement',
    maxReadData: 'Consultation des données',
    maxBackupData: 'Sauvegarde des données',
    maxUsers: 'Nombre d\'utilisateurs',
    LICENSE_KEY_KimoCLOUDFREE: 'Niveau 4',
    LICENSE_KEY_MC1: 'Niveau 1',
    LICENSE_KEY_MC2: 'Niveau 2',
    LICENSE_KEY_MC3: 'Niveau 3',
    LICENSE_KEY_MC4: 'Niveau 4',
    LICENSE_KEY_TL4: 'Niveau 4',
    max: 'max.',
    month: 'mois',
    slidingMonth: 'mois glissants',
    renew: 'Modifier / Renouveler'
  },
  ConfigurePage: {
    serial: 'N° de série',
    version: 'Version',
    unit: 'Unité',
    loraNetwork: 'Réseau Lora',
    configureDevice: 'Configuration',
    configureSuccess: 'Configuration de l\'appareil réussie',
    configureError: 'Erreur de configuration',
    configureServer: 'Configuration envoyée au serveur',
    configureChannels: 'Configuration des voies',
    informationDevice: 'Appareil',
    Designation: 'Nom',
    Intervals: 'Intervalles',
    IntervalMesure: 'Intervalle de mesure',
    IntervalEnregistrement: 'Intervalle d\'enregistrement',
    DepartType: 'Type de Départ',
    DepartType_0: 'Par date',
    DepartType_1: 'Bouton',
    DepartType_2: 'Immediat',
    DateEtHeureDepart: 'Date de Départ',
    Enregistrement: 'Enregistrement',
    Display: 'Affichage',
    Infos: 'Information de l\'appareil',
    Leds: 'LEDs',
    Activated: 'Activé',
    Proteged: 'Protégé',
    Fonctionnement: 'Fonctionnement',
    ConfigurationAllreadyProgramed: 'Une configuration est déjà en cours',
    seuilEntre: 'Seuil entre {0} et {1} {2}',
    tempo: 'Temporisation',
    comments: 'Commentaires',
    dataset: 'Campagne',
    record: 'Enregistrer',
    recordMode: 'Mode d\'enregistrement',
    recordMode_1: 'Instantané',
    recordMode_2: 'Minimum',
    recordMode_3: 'Maximum',
    recordMode_4: 'Moyenne',
    stopByButton: 'Arrêt par bouton',
    hours: 'Heure(s)',
    minutes: 'Minute(s)',
    seconds: 'Seconde(s)',
    enableThresholds: 'Activer seuils',
    low: 'Bas',
    high: 'Haut',
    thresholds: 'Seuils alarme',
    ERROR_417: 'Erreur 417 inconnue',
    ERROR_430: 'Une configuration est déjà en cours',
    ERROR_408: 'Configuration impossible : le KILOG ne semble pas connecté au CLOUD',
    ERROR_512: 'Erreur 512 inconnue',
    ERROR_500: 'Erreur 500 inconnue',
    ERROR_220: 'Erreur 220 inconnue',
    success: 'Configuration envoyée avec succés',
    loadConfiguration: 'Charger une configuration',
    validmulti:'**Configuration multiple',
    validmultihelp: '**Envoyer cette configuration à une selection d\' appareils compatibles de ce site',

    INVALID_DATE_TIME: '**Format de date invalide: DD/MM/YYYY HH:MM',
    cfr21dialogTitle: 'Identification et justification',
    cfr21dialogDesc: 'Merci de vous identifier avant de procéder au changement de configuration',
    cfr21dialogPasswordLabel: 'Votre mot de passe',
    cfr21dialogCommentLabel: 'La justification pour ce changement de configuration',
    cfr21dialogerror_fields: 'Tous les champs doivent obligatoirement être renseignés.',

    templatedialogTitle:'Sélectionner un modèle de configuration',
    templatedialogDesc: 'Veuillez sélectionnez un modèle de configuration ci dessous. Celui ci sera appliqué à l\'appreil choisi.',
    templatedialogLabel: 'Liste des configurations compatibles avec votre appareil',
    templatedialogerror_fields: 'Aucune configuration n\'a été sélectionnée.',


    // erreurs de formulaire de configuration générale
    // normalement, l'appli ne voit jamais ces erreurs
    INVALID_CONFIG_FORMAT: 'Configuration invalide, annulation', // si les objets, types, ... ne sont pas ceux attendus,    
    NO_CANAL_CONFIG: 'Aucun canal de configuration défini', // si pas de Canal_Config, (ie undefined)
    NO_MODE: 'Aucun mode d\'affichage de défini',
    NO_RECORD_TYPE: "Aucun type d'enregistrement défini.",
    NO_START_TYPE: 'Aucun type de départ défini',
    NO_MESURE_TIME: 'Durée de mesure non définie',
    NO_RECORD_TIME: 'Durée d\'enregistrement non définie',
    NO_CAMPAGNE_NAME: 'Aucun nom de campagne de défini',
    
    // erreurs sur les champs du formulaire de configuration
    INVALID_CANAL: 'Canal de configuration invalide', // si != 0,1,2,3
    INVALID_MODE: 'Mode d\'affichage invalide', // si <0 ou >2
    INVALID_LED_ALARM: 'Aucun mode LED pour les alarmes de défini.',
    INVALID_LED_ON: 'Aucun mode LED pour le voyant actif de défini', // ceux la aussi, ce serait étonnant qu'elles sortent
    INVALID_CAMPAGNE_NAME_LENGTH: 'Le nom de campagne doit faire au minimum 3 caractères et au maximum 20',
    INVALID_RECORD_TIME: 'Durée d\'enregistrement non valide',
    INVALID_MESURE_TIME: 'Durée de mesure invalide: doit etre compris entre ...',
    INVALID_RECORD_TYPE: 'Type d\'enrgistrement de mesure invalide.',
    INVALID_START_TYPE: 'le type de départ doit être par date, par bouton ou immédiat',
    INVALID_DATE_FORMAT: 'Format de la date de départ incorrect',
    INVALID_SEUIL_FORMAT: 'Format de seuil invalide: doit etre un nombre strictement positif',
    INVALID_TEMPO_FORMAT: 'Format de temporisation invalide: doit etre un nombre strictement positif.',
    INVALID_CHANNEL_NAME: 'Nom de voie invalide: doit faire au maximum 15 caractères',
    INVALID_CHANNEL_NUMBER: 'Numéro de voie invalide',
    INVALID_CHANNEL_REF_PROBE:'Type de sonde inconnue',
    INVALID_CHANNEL_UNIT: 'Unité de la voie inconnue',
    XML_CONFIG_NO_TOKEN: 'Aucun token de défini pour une configuration xml',
    RECORD_LT_MESURE: 'La durée d\'enregistrement ne peut pas être inférieure à la durée de mesure',
    NO_DATE_GIVEN: 'Aucune date de départ pour la campagne n\'a été renseignée',    
    INVALID_NO_CHANNEL: 'Aucune voie de séléctionnée pour les enregistrements',
    INVALID_SEUILS_VALUES: 'Le seuil HAUT ne peut etre superieur au seuil BAS',

    // uniquement dédiée au support de la CFR
    NO_CFR_DATAS: 'Aucunes informations d\'identification n\'ont été fournies',
    CONFIG_NOT_LOGGED: 'Not loggin!', // normalement, cette erreur est récupérée avant d'envoyée la configuration
    CONFIG_UNKNOWN_USER: 'Les informations d\'identifications fournies sont érronées.',

    // erreur serveur inconnue
    'unknown': 'Erreur serveur inconnue...',
  },
  SlaveConfiguration: {
    full: 'Configuration complète',
    LaunchFull: 'Lancer la reconfiguration complète par XML',
    warningText1: 'Attention ! Nous vous conseillons d\'utiliser l\'application mobile Kimo Cloud pour changer les paramètres de vos appareils. Elle vous permettra de configurer votre appareil plus facilement.',
    warningText2: ' Vous pouvez également suivre les instructions de cet assistant pour configurer votre appareil par fichier XML',
    simplified: 'Configuration simplifiée',
  },
  ProbesType: {
    Probe_1: 'Température CTN d\'ambiance',
    Probe_2: 'Température CTN interne',
    Probe_3: 'Température CTN déportée',
    Probe_4: 'Courant 0-20mA',
    Probe_5: 'Courant 4-20mA',
    Probe_6: 'Tension 0-10V',
    Probe_7: 'Tension 0-2500mV',
    Probe_8: 'Thermo-Hygro SHT d\'ambiance',
    Probe_9: 'Thermo-Hygro SHT déportée',
    Probe_10: 'Lumière',
    Probe_11: 'Température Thermocouple K',
    Probe_12: 'Température Thermocouple T',
    Probe_13: 'Température Thermocouple J',
    Probe_14: 'Température PT100 déportée',
    Probe_15: 'Thermo-Hygro d\'ambiance',
    Probe_16: 'Thermo-Hygro inox déportée',
    Probe_17: 'Pince ampèremétrique 20A',
    Probe_18: 'Pince ampèremétrique 50A',
    Probe_19: 'Pince ampèremétrique 100A',
    Probe_20: 'Pince ampèremétrique 200A',
    Probe_21: 'Pince ampèremétrique 600A',
    Probe_22: 'Thermo-Hygro plastique déportée',

    //Sonde Température KT20
    Probe_23: 'Température KT20',

    //Sondes Kistocks RF 
    Probe_24: 'Température Thermocouple S',
    Probe_25: 'Détection d\'impulsions',
    Probe_26: 'Compteur d\'impulsions',
    Probe_27: 'Pression 1000Pa',
    Probe_28: 'Pression 10000Pa',
    Probe_29: 'Cellule CO2',
    Probe_30: 'Lumière',

    Probe_lora_1: 'Thermocouple K',
    Probe_lora_2: 'Thermocouple J',
    Probe_lora_3: 'Thermocouple T',
    Probe_lora_4: 'Thermocouple N',
    Probe_lora_5: 'Thermocouple S',
    Probe_lora_6: 'Courant 0-20mA',
    Probe_lora_7: 'Courant 4-20mA',
    Probe_lora_8: 'Tension 0-5V',
    Probe_lora_9: 'Tension 0-10V',
    Probe_lora_10: 'Compteur impulsion',
    Probe_lora_11: 'Pince ampèremétrique 50A',
    Probe_lora_12: 'Pince ampèremétrique 100A',
    Probe_lora_13: 'Pince ampèremétrique 200A',
    Probe_lora_14: 'Pince ampèremétrique 600A',
    Probe_lora_15: 'Température CTN externe',
    Probe_lora_16: 'température PT100 externe',
    Probe_lora_17: 'Température interne',
    Probe_lora_18: 'Pression d\'eau 0-10 bar',
    Probe_lora_19: 'Sonde hygro-température',
    Probe_lora_20: 'Sonde hygro-température inox',
    Probe_lora_21: 'Sonde hygro-température ABS/amb',
    Probe_lora_22: 'Sonde hygro-température interne',
    Probe_lora_23: 'Lumière interne',
    Probe_lora_24: 'CO2 interne',
    Probe_lora_25: 'Pression atmosphérique interne',
    Probe_lora_26: 'Pression interne 1000 Pa',
    Probe_lora_27: 'Pression interne 10000 Pa',
    Probe_lora_28: 'Pression d\'eau 0-20 bar',
  },
  VisTimeline: {
    title: 'Périodes signées',
    sign_datas: 'Signer la periode',
  },
  VisTimeline_dlg :{
    dlg_sign_title: 'Signer les mesures sur la periode sélectionnée',
    cancel: 'Annuler',
    save: 'Signer',
    device_label: 'Nom',
    device_serial: '**Numéro de série',
    from:'Du',
    to:'Au',
    reason: 'Raison',
    password:'Mot de passe',
    reason_text: 'Justification de la signature',
    password_text: 'Veuillez entrer votre mot de passe pour valider l\'autentification',
    comment:'Commentaires',
    comment_text:'Une courte phrase (max: 200 chars) pour expliquer les données (optionnel)',
    examen: 'Examen',
    approbation:'Approbation',
    responsabilite:'Responsabilité',
    paternite:'Paternité',
  },
  signature_arry : {
    date:'Date',
    period: 'Période',
    who: 'Utilisateur',
    reason: 'Raison',
    reason1: 'Examen',
    reason2:'Approbation',
    reason3:'Responsabilité',
    reason4:'Paternité',
    comment:'Commentaires'
  },
  AssistantConfiguration:{
    title: '**Identification de l\'appareil',
    description: '**Indiquez le numéro de série et le code de l’appareil. Ces informations se trouvent à l’arrière du boîtier de l’enregistreur.',
    code_app: '**Code appareil',
    serial: '**Numéro de série',
    devicetype: '**Type de l\'appareil',
    devicetype_placeholder: '**Choisir le type d\'appareil',
    radio_ble: '**Configuration par l\'application mobile (Conseillé)',
    radio_xml: '**Configuration par fichier XML',

    p2_title: '**Configuration de l\'appareil',
    p2_info_1: '**Afin de continuer le mise en route de votre appareil, nous vous conseillons d\'utiliser l\'application mobile Kimo Cloud for All. Elle vous permettra de configurer votre appareil plus facilement.',
    p2_info_2: '**Vous pouvez également suivre les instructions de cet assistant pour configurer votre appareil par fichier XML.',

    p2_description:'**Connectez votre appareil en USB à l’ordinateur. Un code de configuration va apparaitre sur l’écran de l’enregistreur, renseignez le ici.',
    p2_code: '**Code de configuration',
    p2_alert: '*Attention ! Ne débranchez pas votre appareil du port USB pendant la configuration, sinon le numéro de configuration ne sera plus valide.',

    p3_title: '**Configuration de l\'appareil',

    p4_title: '**Enregistrement de la configuration',
    p4_end_head: '**Le fichier de configuration conf',
    p4_end_tail: '.xml a été enregistré sur votre ordinateur. Copiez ce fichier sur votre enregistreur, affiché sur votre ordinateur dans les stockages amovibles.',
    p4_alert: '**Attention ! Si votre navigateur est configuré de manière à télécharger automatiquement les fichiers, vous trouverez votre fichier dans le dossier de téléchargement habituel.',

    p5_title: '**Placement de l\'appareil',
    p5_instructions: '**Une fois le fichier de configuration copié sur votre appareil, celui-ci est prêt à fonctionner. Donnez lui une désignation et sélectionnez la zone dans laquelle vous souhaitez l’intégrer.',

    error_417:'**Erreur de données du formulaire',
    
  },
  AssistantComponent:{
    prev: '**Précédent',
    end: '**Terminer',
    next: '**Suivant'
  },
  OldPasswordForm: {
    connexion: '**Mettre à jour le mot de passe',
    title: '**Mise à jour du mot de passe',
    hello: '**Bonjour ',
    more: ' **La norme CFR-21 implique de modifier les passwords lors de votre première connexion et au moins tous les 90 jours, ....',
    tooold: '**trop vieux',
    firstconnect: '**Première connexion',
    oldpassword: '**Votre ancien mot de passe',
    newpassword: '**Votre nouveau mot de passe',
    replaypassword: '**Confirmer votre nouveau mot de passe',
    ERROR_CONFIRMATION_MISMATCH: '**Le nouveau mot de passe ne peut pas etre le meme que l\'ancien!',
    ERROR_DIFFERENT_PASSWORD: '**ERROR_DIFFERENT_PASSWORD',
    errorTooShort:'Un mot de passe doit faire au minimum 6 caractères.',
    ALREADY_USED_PASSWORD:'Vous avez déjà utilisé ce mot de passe récement. Merci d\'en choisir un autre.',
  },
  MultiConfiguration: {
    title:'**Configurations multiples',
    description_compat: '**Selectionner dans la liste ci-dessous le ou les appareils a configurer',
    description_working: '**La configuration est envoyée au serveur. Cette opération peut prendre quelques minutes, merci de patienter.',
    no_slaves:'**Aucun appareil compatible n\'a été trouvé sur ce site.',
    conf_ok:'**Les configurations ont été enregistrées sur le serveur. Elles seront envoyées aux appareils au prochain retour de données.'
  }
};