module.exports = {
	"alarms.title": "Alarmes",
	"alarms.date": "Date",
	"alarms.slave": "Appareil",
	"alarms.channel": "Voie",
	"alarms.comment": "Commentaire",
	"alarms.techalarm_1": "Batterie changée",
	"alarms.techalarm_2": "Batterie faible",
	"alarms.techalarm_3": "Perte de communication",
	"alarms.techalarm_4": "Communication rétablie",
	"channelStats.min": "Min",
	"channelStats.max": "Max",
	"channelStats.average": "Moyenne",
	"channelStats.deviation": "Ecart type",
	"channelStats.mkt": "MKT",
	"channel.name": "Désignation",
	"channel.measure": "Mesure",
	"channel.probe": "Mesure",
	"channel.lowThreshold": "Seuil bas",
	"channel.highThreshold": "Seuil haut",
	"channel.title": "Voies enregistrées",
	"logEvents.title": "Evènements",
	"logEvents.date": "Date",
	"logEvents.user": "Utilisateur",
	"logEvents.source": "Source",
	"logEvents.source_0": "Application",
	"logEvents.source_1": "Appareil",
	"logEvents.source_2": "Alarme Deportée",
	"logEvents.source_3": "Voie Calculée",
	"logEvents.source_4": "Base De Communication",
	"logEvents.source_5": "Cloud",
	"logEvents.code_1": "Application Lancée",
	"logEvents.code_2": "Application Fermée",
	"logEvents.code_3": "Modification Préférences",
	"logEvents.code_4": "Modification Paramètres Messagerie",
	"logEvents.code_10": "Connexion Utilisateur",
	"logEvents.code_11": "Deconnexion Utilisateur",
	"logEvents.code_12": "Connexion Echouée",
	"logEvents.code_13": "Ajout Utilisateur",
	"logEvents.code_14": "Modification Utilisateur",
	"logEvents.code_15": "Suppression Utilisateur",
	"logEvents.code_16": "Changement Password",
	"logEvents.code_17": "Ajout Groupe",
	"logEvents.code_18": "Modification Groupe",
	"logEvents.code_19": "Suppression Groupe",
	"logEvents.code_20": "Gestion Utilisateurs Modifiée",
	"logEvents.code_100": "Appairage Appareil RF",
	"logEvents.code_101": "Suppression Appareil RF",
	"logEvents.code_102": "Remplacement Appareil RF",
	"logEvents.code_103": "Placement Appareil RF",
	"logEvents.code_104": "Retrait Appareil RF",
	"logEvents.code_105": "Griser Appareil RF",
	"logEvents.code_106": "Degriser Appareil RF",
	"logEvents.code_107": "Configuration Verification Reseau",
	"logEvents.code_108": "Planification Vidages",
	"logEvents.code_109": "Planification Mesures",
	"logEvents.code_201": "Configuration Appareil",
	"logEvents.code_202": "Dechargement Appareil",
	"logEvents.code_203": "Lancement Campagne Par PC",
	"logEvents.code_204": "Arrêt Campagne Par PC",
	"logEvents.code_205": "Vidage Appareil",
	"logEvents.code_206": "Lecture Mesures Appareil",
	"logEvents.code_207": "Test Communication",
	"logEvents.code_1001": "Produit Ajouté",
	"logEvents.code_1002": "Infos Produit Modifiées",
	"logEvents.code_1003": "Produit Supprime",
	"logEvents.code_2001": "Alarme Deportée Ajoutée",
	"logEvents.code_2002": "Alarme Deportée Modifiée",
	"logEvents.code_2003": "Alarme Deportée Supprimée",
	"logEvents.code_2004": "Pilotage Relais Appareil",
	"logEvents.code_2005": "Alarme Email Ajoutée",
	"logEvents.code_2006": "Alarme Email Modifiée",
	"logEvents.code_2007": "Alarme Email Supprimée",
	"logEvents.code_2008": "Alarme Email Envoyée",
	"logEvents.code_3001": "Démarrage Service",
	"logEvents.code_3002": "Arrêt Service",
	"logEvents.code_5001": "Connexion échouée",
	"logEvents.code_5002": "Connexion rétablie",
	"logEvents.code_5003": "Echec envoi de données",
	"logEvents.code_5004": "Requête au serveur",
	"logEvents.category": "Catégorie",
	"logEvents.description": "Description",
	"logEvents.comment": "Commentaire",
	"measures.title": "Relevés",
	"measures.index": "Index",
	"measures.date": "Date",
	"slaveSettings.title": "Configuration",
	"slaveSettings.logType": "Type de mesure",
	"slaveSettings.measureInterval": "Intervalle",
	"slaveSettings.count": "Nombre de points",
	"slaveSettings.min": "Date de départ",
	"slaveSettings.max": "Date de fin",
	"slaveSettings.comment": "Commentaire",
	"slave.title": "Appareil",
	"slave.name": "Désignation",
	"slave.slaveNumber": "N° d'appareil",
	"slave.reference": "Type d'appareil",
	"slave.serial": "N° de série",
	"slave.version": "Version de soft",
	"minutes": "minutes",
	"channel.unit_0": "aucune",
	"channel.unit_1": "m/s",
	"channel.unit_2": "fpm",
	"channel.unit_3": "m3/h",
	"channel.unit_4": "L/s",
	"channel.unit_5": "cfm",
	"channel.unit_6": "m3/s",
	"channel.unit_7": "°C",
	"channel.unit_8": "°F",
	"channel.unit_9": "%RH",
	"channel.unit_10": "%PSI",
	"channel.unit_11": "Pa",
	"channel.unit_12": "mmH2O",
	"channel.unit_13": "inWg",
	"channel.unit_14": "kPa",
	"channel.unit_15": "mmHg",
	"channel.unit_16": "mbar",
	"channel.unit_17": "absolueg/kg",
	"channel.unit_18": "°C Td",
	"channel.unit_19": "°F Td",
	"channel.unit_20": "°C Tw",
	"channel.unit_21": "°F Tw",
	"channel.unit_22": "kJ/kg",
	"channel.unit_23": "mA",
	"channel.unit_24": "A",
	"channel.unit_25": "mV",
	"channel.unit_26": "V",
	"channel.unit_27": "lux",
	"channel.unit_31": "unité libre",
	"channel.unit_32": "pulse",
	"channel.unit_33": "pulses",
	"channel.unit_34": "KelvinK",
	"channel.unit_35": "km/h",
	"channel.unit_36": "mph",
	"channel.unit_37": "Hz",
	"channel.unit_38": "tr/min",
	"channel.unit_39": "rpm",
	"channel.unit_40": "m/min",
	"channel.unit_41": "in/min",
	"channel.unit_42": "bar",
	"channel.unit_43": "daPa",
	"channel.unit_44": "hPa",
	"channel.unit_45": "ppm",
	"channel.unit_46": "dB",
	"channel.unit_47": "ohms",
	"channel.unit_undefined": "Indéfinie",
	"channel.unit_lora_0": "aucune",
	"channel.unit_lora_1": "%RH",
	"channel.unit_lora_2": "",
	"channel.unit_lora_3": "unité libre",
	"channel.unit_lora_15": "unité inconnue",
	"channel.unit_lora_16": "°C",
	"channel.unit_lora_17": "°F",
	"channel.unit_lora_18": "K",
	"channel.unit_lora_19": "Delta °C",
	"channel.unit_lora_20": "Delta °F",
	"channel.unit_lora_32": "%RH",
	"channel.unit_lora_33": "g/kg",
	"channel.unit_lora_34": "kJ/kg",
	"channel.unit_lora_35": "°CTd",
	"channel.unit_lora_36": "°FTd",
	"channel.unit_lora_37": "°C Tw",
	"channel.unit_lora_38": "°F Tw",
	"channel.unit_lora_39": "g/m3",
	"channel.unit_lora_48": "bar",
	"channel.unit_lora_49": "PSI",
	"channel.unit_lora_50": "kPa",
	"channel.unit_lora_51": "inWg",
	"channel.unit_lora_52": "hPa",
	"channel.unit_lora_53": "mbar",
	"channel.unit_lora_54": "mmHg",
	"channel.unit_lora_55": "mmH2O",
	"channel.unit_lora_56": "daPa",
	"channel.unit_lora_57": "Pa",
	"channel.unit_lora_64": "m/s",
	"channel.unit_lora_65": "fpm",
	"channel.unit_lora_66": "km/h",
	"channel.unit_lora_67": "mph",
	"channel.unit_lora_80": "m3/h",
	"channel.unit_lora_81": "l/s",
	"channel.unit_lora_82": "cfm",
	"channel.unit_lora_83": "m3/s",
	"channel.unit_lora_84": "nm3/h",
	"channel.unit_lora_85": "dm3/h",
	"channel.unit_lora_96": "Hz",
	"channel.unit_lora_97": "tr/min",
	"channel.unit_lora_98": "rpm",
	"channel.unit_lora_99": "m/min",
	"channel.unit_lora_100": "in/min",
	"channel.unit_lora_101": "ft/min",
	"channel.unit_lora_102": "m/s",
	"channel.unit_lora_112": "ppm",
	"channel.unit_lora_113": "mg/m3",
	"channel.unit_lora_114": "mg/kWh",
	"channel.unit_lora_115": "g/kWh",
	"channel.unit_lora_116": "g/GJ",
	"channel.unit_lora_117": "g/m3",
	"channel.unit_lora_118": "%",
	"channel.unit_lora_119": "% LIE",
	"channel.unit_lora_120": "g/an",
	"channel.unit_lora_128": "lux",
	"channel.unit_lora_129": "fc",
	"channel.unit_lora_130": "W/m2",
	"channel.unit_lora_131": "klux",
	"channel.unit_lora_132": "kfc",
	"channel.unit_lora_144": "db",
	"channel.unit_lora_160": "mV",
	"channel.unit_lora_161": "V",
	"channel.unit_lora_162": "µA",
	"channel.unit_lora_163": "mA",
	"channel.unit_lora_164": "A",
	"channel.unit_lora_165": "Ohms",
	"channel.unit_lora_176": "wbgt",
	"channel.unit_lora_177": "W/m2/K",
	"channel.unit_lora_192": "s",
	"channel.unit_lora_193": "min",
	"channel.unit_lora_194": "h",
	"channel.unit_lora_208": "mm",
	"channel.unit_lora_209": "in",
	"channel.unit_lora_210": "m",
	"channel.unit_lora_255": "Comptage",
	"channel.probecodes_1": "Température CTN Ambiance",
	"channel.probecodes_2": "Température CTN Interne",
	"channel.probecodes_3": "Température CTN Déportée",
	"channel.probecodes_4": "Courant 0/20 mA",
	"channel.probecodes_5": "Courant 4/20 mA",
	"channel.probecodes_6": "Tension 0/10 V",
	"channel.probecodes_7": "Tension 0/2500 mV",
	"channel.probecodes_8": "Thermo-Hygro SHT Ambiance",
	"channel.probecodes_9": "Thermo-Hygro SHT Déportée",
	"channel.probecodes_10": "Luminosité",
	"channel.probecodes_11": "Température Thermocouple K",
	"channel.probecodes_12": "Température Thermocouple T",
	"channel.probecodes_13": "Température Thermocouple J",
	"channel.probecodes_14": "Température PT100 Déportée",
	"channel.probecodes_15": "Thermo-Hygro Ambiance",
	"channel.probecodes_16": "Thermo-Hygro Inox Déportée",
	"channel.probecodes_17": "Pince ampèremétrique 20 A",
	"channel.probecodes_18": "Pince ampèremétrique 50 A",
	"channel.probecodes_19": "Pince ampèremétrique 100 A",
	"channel.probecodes_20": "Pince ampèremétrique 200 A",
	"channel.probecodes_21": "Pince ampèremétrique 600 A",
	"channel.probecodes_22": "Thermo-Hygro Plastique Déportée",
	"channel.probecodes_23": "Température KT20",
	"channel.probecodes_24": "Température Thermocouple S",
	"channel.probecodes_25": "Détection impulsions",
	"channel.probecodes_26": "Compteur impulsions",
	"channel.probecodes_27": "Pression 1000 Pa",
	"channel.probecodes_28": "Pression 10000 Pa",
	"channel.probecodes_29": "Cellule CO2",
	"channel.probecodes_30": "Lumière",
	"channel.probecodes_lora_1": "Thermocouple K",
	"channel.probecodes_lora_2": "Thermocouple J",
	"channel.probecodes_lora_3": "Thermocouple T",
	"channel.probecodes_lora_4": "Thermocouple N",
	"channel.probecodes_lora_5": "Thermocouple S",
	"channel.probecodes_lora_6": "Courant 0-20mA",
	"channel.probecodes_lora_7": "Courant 4-20mA",
	"channel.probecodes_lora_8": "Tension 0-5V",
	"channel.probecodes_lora_9": "Tension 0-10V",
	"channel.probecodes_lora_10": "Compteur impulsion",
	"channel.probecodes_lora_11": "Pince ampèremétrique 50A",
	"channel.probecodes_lora_12": "Pince ampèremétrique 100A",
	"channel.probecodes_lora_13": "Pince ampèremétrique 200A",
	"channel.probecodes_lora_14": "Pince ampèremétrique 600A",
	"channel.probecodes_lora_15": "Température CTN externe",
	"channel.probecodes_lora_16": "température PT100 externe",
	"channel.probecodes_lora_17": "Température interne",
	"channel.probecodes_lora_18": "Pression d'eau 0-10 bar",
	"channel.probecodes_lora_19": "Sonde hygro-température",
	"channel.probecodes_lora_20": "Sonde hygro-température inox",
	"channel.probecodes_lora_21": "Sonde hygro-température ABS/amb",
	"channel.probecodes_lora_22": "Sonde hygro-température interne",
	"channel.probecodes_lora_23": "Lumière interne",
	"channel.probecodes_lora_24": "CO2 interne",
	"channel.probecodes_lora_25": "Pression atmosphérique interne",
	"channel.probecodes_lora_26": "Pression interne 1000 Pa",
	"channel.probecodes_lora_27": "Pression interne 10000 Pa",
	"channel.probecodes_lora_28": "Pression d'eau 0-20 bar",
	"measures.stats": "Statistiques",
	"slaveSettings.logtype_0": "Différé",
	"slaveSettings.logtype_1": "Instant",
	"slaveSettings.logtype_2": "Minimum",
	"slaveSettings.logtype_3": "Maximum",
	"slaveSettings.logtype_4": "Moyenne",
	"slaveSettings.logtype_5": "Surveillance",
	"slaveSettings.logtype_6": "EnLigne",
	"slaveSettings.logtype_7": "Fin",
	"slaveSettings.logtype_8": "Thermometre",
	"slaveSettings.logtype_9": "Thermohygrometre",
	"slaveSettings.logtype_10": "Detection d'impulsions",
	"chart.title": "Graphique",
	"chart.nodata": "Pas de données",
	"logEvents.source_undefined": "Indéfini",
	"csv.name": "Nom du site",
	"csv.serial": "Identifiant du site",
	"channel.probecodes_undefined": "channel.probecodes_undefined",
	"channel.probecodes_lora_a17": "Température interne",
	"channel.probecodes_lora_a20": "Sonde hygro-température inox",
	"alarms.techalarm_0": "Alarme inconnue"
}